### ISSUE TITLE
Table-data Browser: column-picking dialog has wrong title

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#281] opened 2018-08-17 11:24 UTC
Home [button] > Data [heading] > View samples [button] > [samples table] > Pick columns

The title of the dialog/modal box says "Pick filter for samples" instead of something like "Pick columns for the samples table".

**Comment by benjeffery** [comment] 2018-09-07 10:54
Interestingly, following your directions gives me a blank title bar.

**Comment by benjeffery** [comment] 2018-09-07 10:55
A modal without title will show the last used modal's title.

**Comment by benjeffery** [comment] 2018-09-07 10:59
`withStyles(styles)` strikes again!

**Comment by benjeffery** [comment] 2018-09-07 11:01
When will its reign of wrapping terror end?! When will innocent components be free to expose their methods and props again? Who will save us?

**Comment by leehart** [comment] 2018-09-07 13:04
This issue was based on the version on staging at the time, which still exhibits the behaviour.
I gather differences since the staging version and the current version would explain the difference seen. (I get a blank title bar too on the current version.)

I suppose that means this issue is invalid, but maybe could be replaced with an issue about blank title bars... I'm happy with this being in situ, as it is.

wrt `withStyles(styles)` ... yeah, a right pain in the architecture. Maybe they'll see the error of their ways. 

Or maybe we're just doing it wrong. I'm not confident we're doing styles right, fwiw.
Then again, I'm not confident I'm doing anything right... Am I doing this wrong? Who will save me from myself!

You are our only hope, Ben!

**Comment by benjeffery** [comment] 2018-09-07 13:09
The difference seen was down to the order of buttons pressed. You must have opened the filter modal for the original issue before the column picker. The issue is still valid and fixed by https://github.com/cggh/panoptes/pull/1165

**Comment by leehart** [comment] 2018-09-07 13:18
I see, so it is!

**Closed** 2018-09-17 10:01 UTC
Labels: MUST, bug
